# Copyright (c) 2026 Takayuki Nagata
# SPDX-License-Identifier: MIT

"""Build-and-run helper for the cocotb testbenches (Icarus Verilog).

Same structure as VUX9K's sim/runners/sim_runner.py: one compiled simulation per
toplevel under build/sim/<sim>/<toplevel>/, one run directory per test.
"""

import fcntl
import os
import subprocess
import sys
from contextlib import contextmanager
from pathlib import Path

from cocotb_tools.runner import get_runner

SIM_DIR = Path(__file__).resolve().parent
REPO_ROOT = SIM_DIR.parent
BUILD_DIR = REPO_ROOT / "build"
VERYL_OUT_DIR = BUILD_DIR / "veryl"
SIM_BUILD_DIR = BUILD_DIR / "sim"
TEST_MODULE_DIR = SIM_DIR / "tests"

# Controller IP (generated by `make veryl`, packages first)
IP_SOURCES = [
    VERYL_OUT_DIR / "rtl" / "psram_pkg.sv",
    VERYL_OUT_DIR / "rtl" / "psram_core.sv",
    VERYL_OUT_DIR / "rtl" / "psram_phy.sv",
    VERYL_OUT_DIR / "rtl" / "psram_controller.sv",
]
MODEL_SOURCES = [
    SIM_DIR / "model" / "w955d8mbya_die.sv",
    SIM_DIR / "model" / "w955d8mbya_model.sv",
]
TOPLEVELS = {
    "tb_psram_controller": IP_SOURCES + MODEL_SOURCES + [SIM_DIR / "tb" / "tb_psram_controller.sv"],
}

BUILD_ARGS = {"icarus": ["-g2012"]}


def _libs_to_preload() -> str:
    """oss-cad-suite's vvp runs under its own ld.so/library path, where the uv-built
    libpython can't find librt/libutil ("librt.so.1: cannot open shared object file")."""
    libs = []
    for name in ("librt.so.1", "libutil.so.1"):
        try:
            path = subprocess.run(["gcc", f"-print-file-name={name}"], capture_output=True, text=True).stdout.strip()
        except FileNotFoundError:
            continue
        if os.path.isabs(path) and os.path.exists(path):
            libs.append(path)
    return " ".join(libs)


@contextmanager
def _exclusive(lock_path: Path):
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with open(lock_path, "w") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(f, fcntl.LOCK_UN)


def run(
    toplevel: str,
    module: str,
    *,
    testcase: str | None = None,
    run_name: str | None = None,
    parameters: dict[str, int] | None = None,
    extra_env: dict[str, str] | None = None,
) -> Path:
    """Compile (if outdated) and run one cocotb test module against toplevel.

    Each set of toplevel parameters gets its own build directory."""
    sim = os.environ.get("SIM", "icarus")
    parameters = parameters or {}
    variant = "_".join([toplevel] + [f"{k}{v}" for k, v in sorted(parameters.items())])
    build_dir = SIM_BUILD_DIR / sim / variant
    test_dir = build_dir / f"run_{run_name or module}"

    sources = TOPLEVELS[toplevel]
    missing = [str(p.relative_to(REPO_ROOT)) for p in sources if not p.exists()]
    if missing:
        raise FileNotFoundError(f"Missing HDL sources (run `make veryl` first): {', '.join(missing)}")

    if str(TEST_MODULE_DIR) not in sys.path:
        sys.path.insert(0, str(TEST_MODULE_DIR))

    runner = get_runner(sim)
    with _exclusive(build_dir.with_name(f"{variant}.lock")):
        runner.build(
            sources=sources,
            hdl_toplevel=toplevel,
            build_dir=build_dir,
            build_args=BUILD_ARGS[sim],
            parameters=parameters,
            timescale=("1ns", "1ps"),
        )

    test_dir.mkdir(parents=True, exist_ok=True)
    env = dict(extra_env or {})
    env["PYTHONPATH"] = os.pathsep.join([str(TEST_MODULE_DIR), os.environ.get("PYTHONPATH", "")])
    preload = _libs_to_preload()
    if preload and "LD_PRELOAD" not in os.environ:
        env["LD_PRELOAD"] = preload
    return runner.test(
        test_module=module,
        hdl_toplevel=toplevel,
        build_dir=build_dir,
        test_dir=test_dir,
        testcase=testcase,
        extra_env=env,
    )
